# input files
task: cv  # cv or debug
drug_feat: output/drug_feat_ae.npy
cell_feat: output/cell_feat_ae.npy
drug2id: data/drug2id.tsv
cell2id: data/cell2id.tsv
synergy: data/syn4cv_lv_d_out_1.csv
sensitivity: data/sen4cv_lv_d_out.csv
dataloader:
  eval_factor: 4 # batch_size *= eval_factor when eval model
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
folds:
  - 0
  - 1
  - 2
  - 3
  - 4
hyper_param:
  batch_size: 512
  epoch: 500
  hidden:
    - 128
    - 256
    - 512
  lr:
    - 1e-3
    - 1e-4
    - 1e-5
  patience: 50
